# SPDX-License-Identifier: MIT
# Copyright (c) 2022, Lukas Kuzmiak

import enum


@enum.unique
class ECJPakeRole(enum.IntEnum):
    CLIENT: ...
    SERVER: ...


class ECJPake:
    def __init__(self) -> None: ...

    def setup(self, role: ECJPakeRole, hash, curve, secret: bytes) -> None: ...

    def check(self) -> None: ...

    def write_round_one(self) -> bytes: ...

    def read_round_one(self, buffer: bytes) -> None: ...

    def write_round_two(self) -> bytes: ...

    def read_round_two(self, buffer: bytes) -> None: ...

    def derive_secret(self) -> bytes: ...

    def self_test(self, verbose: bool) -> None: ...
